### ISSUE TITLE
Deploy and install Vitro 1.9.3 to VM

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto#32]
Steps are taken in part from https://wiki.duraspace.org/display/VIVODOC19x/Installing+VIVO and https://wiki.duraspace.org/display/VIVODOC19x/SPARQL+Update+API#SPARQLUpdateAPI-EnablingtheAPI

- [x] Clone Vitro
- [x] Create copy of Vitro settings.xml and configure required values
- [x] Create directory to hold Vitro installation
- [x] Create puppet PR (done by @kamchan -- sul-dlss/puppet#3009)
  - [x] Create MySQL database (done by @kamchan as part of #31)
  - [x] Create MySQL credentials and grant access to database (done by @kamchan as part of #31)
  - [x] Install maven 
  - [x] Set JVM parameters
  - [x] Set security limits (increase # of threads for Apache and Tomcat users)
  - [x] Edit Tomcat server.xml to set URI encoding to `UTF-8`
  - [x] Edit Tomcat server.xml to increase `maxPostSize` for the port 8080 connector to `10485760`
- [x] Enable SPARQL Update API in Vitro
- [x] Authorize admin users to use SPARQL Update API
- [x] Run install task 
- [x] Configure the home/config directories (and enable TDB vs. the default SDB)
- [x] Restart Tomcat
- [x] Confirm Apache is proxying Tomcat (w/ Shib) at https://rialto-vitro-dev.stanford.edu/vitro 
- [x] Confirm Vitro starts up w/o worrisome error messages
- [x] Create an initial root user in Vitro
- [x] Create admin users for RIALTO team

**Comment by mjgiarlo** [comment]
This is now complete.
