### ISSUE TITLE
DECOMISSIONING: Overall plan

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto#340]
- [ ] Evaluate export options for Neptune data #335
- [ ] Move pre-transformed data into local storage #338
- [ ] Archive/move repos to sul-dlss-deprecated #339 
- [ ] Work with Ops to shut down services #337
- [ ] Write up documentation #336
